
deploymentsGeneral:
  enableAffinity: false # default is true

# version: "1.0"

jobs:
  busybox:
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
    containers:
    - name: busybox
      image: busybox
      imageTag: latest
      resources:
        limits:
          cpu: 10m
          memory: 128Mi
        requests:
          cpu: 1m
          memory: 64Mi
      command:
        - ls
      args:
        - -la
        - /dir1
        - /dir2
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      volumeMounts:
      - name: dir1
        mountPath: /dir1
      - name: dir2
        mountPath: /dir2
    volumes:
    - name: dir1
      type: hostPath
      hostPath:
        path: /mnt/data
        type: DirectoryOrCreate
    - name: dir2
      type: emptyDir
      sizeLimit: 1Mi
      medium: Memory
